### ISSUE TITLE
Driver installation prevents host from reading modem firmware name & revision.

### ISSUE THREAD

**Issue by RanchoHam** [on7lds/NextionDriverInstaller#1]
I installed the NextionDriver into a Pi-Star 3.4.17 system using the Installer.  After reboot, the host could no longer read the modem firmware name and revision.  The modem is a clone of the MMDVM_HS_DUAL_HAT configured in full RF duplex with a serial repeater in the STM32 chip.    By moving the NextionDriver off of /dev/ttyAMA0 to /dev/serial1, I was able to regain the use of the modem.

Considering I'm drinking from a firehose here, I think I have made great strides in getting the board to work in full duplex, but nothing I've tried so far has made the Nextion NX3224K024 change.

BTW, an uninstall script to roll back the changes would be appreciated.

Thanks,
Rich, WB0NRE

**Comment by ghost** [comment]
I do also run a similar sytem to yours, (Pi 3B, Clone MMDVM, 2.4" Nextion (clone);  
and I had NO problems with Pi-Star reading modem's FW / Rev.
Have you configured like showing below??
(L2 or L3 depend on Nextion layout you have loaded to it)


![NEXTION_DRIVER_CONFIG_PISTAR](https://user-images.githubusercontent.com/29952963/59448957-6a8bb700-8e06-11e9-9343-e64a714ba1f9.png)

If so,
Does Nextion Section within MMDVMHOST expert editing show like this?:
![NEXTION_DRIVER_CONFIG_PISTAR_2](https://user-images.githubusercontent.com/29952963/59449348-264ce680-8e07-11e9-9892-0ef9955b38ba.png)

If so,
Was it working previously?
What connection is you Nextion attached to?

BTW,
This assitance request, maybe will be better "hosted" at:
 [https://forum.pistar.uk/viewforum.php?f=20&sid=386073b3e09865958845f34b00dd0ddb](url)
As far as I think...

I hope that helps!
73'Rafa.
EA3BIL

**Comment by RanchoHam** [comment]
I guess I should look at my messages reasonably often!  I'm not sure what I did, but I am now using several Nextion displays with several different RF boards without trouble.
