### ISSUE TITLE
Default of LogLevel=4 filling up Logs

### ISSUE THREAD

**Issue by BotsWithLasers** [on7lds/NextionDriverInstaller#3]
Default of verbose logging with LogLevel=4 in the https://github.com/on7lds/NextionDriverInstaller/blob/master/NextionDriver.cfg file causes systems running PiStar or other images with tmpfs log and systemd journal directories to run out of space.

Can default level be set to something a little more reasonable? Or install instructions changed to warn users to change it to LogLevel 2 after install.   

So users aren't left wondering why their devices crash after 2-3 hours of use.

**Comment by on7lds** [comment]
Indeed, this gave issues.
I changed the default loglevel to 2
